workflows:
  android-apk:
    name: Android APK Build

    environment:
      node: latest
      java: 21

    scripts:
      - name: Install dependencies and build APK
        script: |
          npm install
          npm run build
          npx cap sync android
          cd android
          ls -la
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab