workflows:
  android-apk:
    name: Android APK Build

    environment:
      node: latest
      java: 17

    scripts:
      - npm install
      - npm run build
      - npx cap sync android
      - cd android
      - ls -la
      - gradle wrapper
      - chmod +x ./gradlew
      - ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab